build:
    environment:
        selenium: true
    project_setup:
        before:
            -
                command: bin/console server:start
    tests:
        override:
            -
                command: vendor/bin/codecept run

checks:
    php:
        code_rating: true
        duplication: true
