build:
    environment:
        selenium: true
    project_setup:
        before:
            -
                command: bin/console server:start

checks:
    php:
        code_rating: true
        duplication: true
