<?php

namespace AppBundle\Repository;

/**
 * BaseEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
