<?php

namespace AppBundle\Repository;

/**
 * PostRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRoleRepository extends \Doctrine\ORM\EntityRepository
{
}
