<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Post;
use AppBundle\Entity\PostRole;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    /**
     * @param string $roleType
     * @param Post $post
     * @param User $user
     */
    public function addRole(string $roleType, Post $post, User $user)
    {
        $role = new PostRole();
        $role->setType($roleType);
        $role->setPost($post);
        $role->setUser($user);

        $entityManager = $this->getEntityManager();
        $entityManager->persist($role);
        $entityManager->flush();
    }
}
