# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.post_voter:
        class:  AppBundle\Security\PostVoter
        tags:
            - { name: security.voter }
        public: false

    app.post_service:
        class: AppBundle\Service\PostService
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@slugify"
