# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.post_voter:
        class:  AppBundle\Security\PostVoter
        tags:
            - { name: security.voter }
        public: false

    app.post_service:
        class: AppBundle\Service\PostService
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@slugify"

    app.unique_for_user_validator:
        class: AppBundle\Validator\Constraints\UniqueForUserValidator
        arguments:
            - "@service_container"
        tags:
            - { name: validator.constraint_validator }

    stringy:
        class: Stringy\Stringy

    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        arguments:
            - '@stringy'
        public: false
        tags:
            - { name: twig.extension }